FROM digrouz/alpine-s6:latest

ARG SABNZBD_VERSION='4.0.0'
ARG PAR2CMDLINE_VERSION='v0.8.1'
ARG UNRAR_VERSION='6.2.6'

LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    SABNZBD_VERSION="${SABNZBD_VERSION}" \
    PAR2CMDLINE_VERSION="${PAR2CMDLINE_VERSION}" \
    UNRAR_VERSION="${UNRAR_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=build-deps \
      make \
      automake \
      autoconf \
      gcc \
      git \
      g++ \
      python3-dev \
      openssl-dev \
      musl-dev \
      libffi-dev \
      curl \
      cargo \
      libxml2-dev\
      libxslt-dev\
    && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      python3 \ 
      py3-six \
      py3-chardet \
      libxml2 \
      libxslt \
      libgomp \
      p7zip \
      py3-pip \
      openssl \
    && \
    pip3 --no-cache-dir install --upgrade setuptools pip wheel && \
    curl -SsL https://github.com/sabnzbd/sabnzbd/releases/download/${SABNZBD_VERSION}/SABnzbd-${SABNZBD_VERSION}-src.tar.gz -o /tmp/SABnzbd.tar.gz && \
    tar xzf /tmp/SABnzbd.tar.gz -C /opt && \
    mv /opt/SABnzbd-${SABNZBD_VERSION} /opt/sabnzbd && \
    cd /opt/sabnzbd && \
    pip3 --no-cache-dir install --upgrade -r /opt/sabnzbd/requirements.txt && \
    python3 tools/make_mo.py && \
    ln -s /config /opt/sabnzbd/.sabnzbd && \
    git clone --depth 1 --branch ${PAR2CMDLINE_VERSION} https://github.com/Parchive/par2cmdline.git /tmp/par2cmdline-mt && \
    cd /tmp/par2cmdline-mt && \
    aclocal && \
    automake --add-missing && \
    autoconf && \
    ./configure && \ 
    make && \
    make install && \
    cd / && \
    rm -rf /tmp/par2cmdline /tmp/par2cmdline-mt && \
    curl -SsL https://www.rarlab.com/rar/unrarsrc-${UNRAR_VERSION}.tar.gz -o /tmp/unrar.tar.gz && \ 
    cd /tmp && \
    tar xzf /tmp/unrar.tar.gz && \
    cd unrar && \
    make -f makefile && \
    install -v -m755 unrar /usr/bin && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    chown -R appuser:appuser /opt/sabnzbd && \
    chmod -R g+w /opt/sabnzbd && \
    rm -rf /opt/sabnzbd/.git* \
           /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* \
           ${HOME}/.cache \
	         ${HOME}/.cargo

### Volume
VOLUME ["/downloads","/config","/incomplete-downloads"]

### Expose ports
EXPOSE 8080 9090
