---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 9090
          volumeMounts:
            - mountPath: /config
              name: sabnzbd-config
            - mountPath: /downloads
              name: sabnzbd-downloads
            - mountPath: /incomplete-downloads
              name: sabnzbd-incomplete-downloads
          env:
            - name: GID
              value: "{{ .Values.service.gid }}"
            - name: UID
              value: "{{ .Values.service.uid }}"
            - name: TZ
              value: "{{ .Values.service.tz }}"
            - name: AUTOUPGRADE
              value: "{{ .Values.service.autoupgrade }}"
            - name: DOCKRELAY
              value: "{{ .Values.smtp.host }}"
            - name: DOCKMAIL
              value: "{{ .Values.smtp.from }}"
            - name: DOCKMAILDOMAIN
              value: "{{ .Values.smtp.domain }}"
      volumes:
        - name: sabnzbd-config
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config-pvc
          {{- else if eq .Values.persistence.config.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.config.nfs.server }}
            path: {{ .Values.persistence.config.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: sabnzbd-downloads
          {{- if eq .Values.persistence.downloads.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-downloads-pvc
          {{- else if eq .Values.persistence.downloads.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.downloads.nfs.server }}
            path: {{ .Values.persistence.downloads.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: sabnzbd-incomplete-downloads
          {{- if eq .Values.persistence.incomplete.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-incomplete-pvc
          {{- else if eq .Values.persistence.incomplete.type "nfs" }}
          nfs:
            server: {{ .Values.persistence.incomplete.nfs.server }}
            path: {{ .Values.persistence.incomplete.nfs.path }}
          {{- else }}
          emptyDir: { }
          {{- end }}
